providers:
  - copernicus:
      name: Copernicus
      description: Copernicus is the European Union's Earth observation programme.
      credentials:
        cdse_username: <your_username>
        cdse_password: <your_password>
      base_urls:
        - base_url: https://catalogue.dataspace.copernicus.eu
        - token_url: https://identity.dataspace.copernicus.eu/auth/realms/CDSE/protocol/openid-connect/token
        - download_url: https://zipper.dataspace.copernicus.eu