apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nimbus-mongodb
  namespace: nimbuschain
spec:
  volumeClaimTemplates:
    - metadata:
        name: mongodb-data
      spec:
        storageClassName: nimbus-local
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 30Gi
