services:
  nimbus-api:
    volumes:
      - ../../src:/app/src

  nimbus-worker:
    volumes:
      - ../../src:/app/src

  nimbus-ui:
    volumes:
      - ../../src:/app/src

  nimbus-zarr:
    volumes:
      - ../../src:/app/src

  nimbus-sen2like:
    volumes:
      - ../../src:/app/src

  nimbus-mask:
    volumes:
      - ../../src:/app/src
