from __future__ import annotations

CUBE_NO_SOURCE_ZARRS = "CUBE_NO_SOURCE_ZARRS"
CUBE_NO_SCENES_IN_DATE_RANGE = "CUBE_NO_SCENES_IN_DATE_RANGE"
CUBE_GROUP_FEWER_THAN_TWO_UNIQUE_TIMES = "CUBE_GROUP_FEWER_THAN_TWO_UNIQUE_TIMES"
CUBE_NO_GROUPS_WITH_MULTIPLE_TIMES = "CUBE_NO_GROUPS_WITH_MULTIPLE_TIMES"
CUBE_SPLIT_ACROSS_TILE_GROUPS = "CUBE_SPLIT_ACROSS_TILE_GROUPS"
CUBE_UNSUPPORTED_LAYOUT_FOR_INPUTS = "CUBE_UNSUPPORTED_LAYOUT_FOR_INPUTS"
CUBE_INPUT_MISSING = "CUBE_INPUT_MISSING"
CUBE_RUNTIME_ERROR = "CUBE_RUNTIME_ERROR"

ZARR_NO_RAW_OUTPUTS = "ZARR_NO_RAW_OUTPUTS"
ZARR_RUNTIME_ERROR = "ZARR_RUNTIME_ERROR"

