apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - pv-mongodb.yaml
  - pv-downloads.yaml

patches:
  - path: patch-downloads-pvc.yaml
  - path: patch-mongodb-statefulset.yaml
  - path: patch-api-deployment.yaml
  - path: patch-worker-deployment.yaml
  - path: patch-api-hpa.yaml
  - path: patch-worker-hpa.yaml
